/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <time.h>
#include "../Inc/master_send.h"

void delay(int second){
	int milsec = 1000 * second;
	clock_t startTime = clock();
	while(clock() < (startTime + milsec));
}

int main(void)
{
	master_send_init();
	while(1){
		delay(1);
		printf("Sending msg\n");
		master_send_msg();
	}
	//printf("hi world\n");
	// for(;;);
}
